# Generated by Django 4.2 on 2023-04-19 16:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_applicant_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_number', models.PositiveIntegerField()),
                ('ownership', models.CharField(choices=[('J', 'Joint'), ('I', 'Individual')], max_length=1)),
                ('category', models.CharField(choices=[('C', 'Commerical'), ('R', 'Residential')], max_length=1)),
                ('load_applied', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Load Applied (in KV)')),
                ('approval_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('C', 'Connection Released'), ('A', 'Approved')], default='P', max_length=1)),
                ('comments', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user.applicant')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_applications', to='user.reviewer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
