# Generated by Django 4.2 on 2023-04-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
