# Generated by Django 4.2 on 2023-04-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
