# Generated by Django 4.2 on 2023-04-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_created_alter_application_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created',
            field=models.DateTimeField(verbose_name='Date of application'),
        ),
    ]
